---
- name: 'Instala banco postgres'
  apt:
    update_cache: yes
    cache_valid_time: 3600 #1 hora
    name: ["postgresql-10", "postgresql-contrib", "python3", "python3-psycopg2"]
    state: installed
  become: yes

- name: "Copiar arquivo pg_hba.cnf"
  copy:
    src: /vagrant/configs/pg_hba.conf
    dest: /etc/postgresql/10/main/pg_hba.conf
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Create a PostgreSQL database user
  postgresql_user: name=postgres password=postgres role_attr_flags=ALL state=present
  become: yes
  become_user: postgres
  become_method: sudo

- name: "Copiar arquivo postgresql.cnf"
  copy:
    src: /vagrant/configs/postgresql.conf
    dest: /etc/postgresql/10/main/postgresql.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
   - restart postgres
