Vagrant.configure("2") do |config|

 
  config.vm.define "java-vm" do |java|
   # configure the basebox
   java.vm.box = "fasmat/ubuntu1804-desktop"
  
    java.vm.network "public_network", ip: "192.168.6.60", bridge: "Intel(R) Ethernet Connection (2) I219-LM"

    java.vm.provision "shell",
      inline: "apt-get update &&  \
               apt-get install -y software-properties-common && \
               apt-get install -y net-tools "

    java.vm.provision "shell",
    inline: "cat /configs/id_java_env.pub >> .ssh/authorized_keys && \
             cp /configs/stsLauncher.desktop /usr/share/applications"

    java.vm.provider "virtualbox" do |vb|
      vb.memory = 8192
      vb.cpus = 4
      vb.name = "Java com Eclipse"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.gui = true
    end
    java.vm.hostname = "java-com-eclipse.local"
    java.vm.synced_folder "./configs", "/configs"
    java.vm.synced_folder "/desenvolvimento/tjmt", "/repositorio"
    java.vm.synced_folder ".", "vagrant", disabled: true

  end

  config.vm.define "java-mint" do |java|
    # configure the basebox
    java.vm.box = "epipho/mint-19.3"
   
     java.vm.network "public_network", ip: "192.168.6.65", bridge: "Intel(R) Ethernet Connection (2) I219-LM"
     java.vm.network "forwarded_port", guest: 8080, host: 8081

     java.vm.provision "shell",
       inline: "apt-get update &&  \
                apt-get install -y software-properties-common && \
                apt-get install -y net-tools && \
                apt-get install snapd"
 
     java.vm.provision "shell",
     inline: "cat /configs/id_java_env.pub >> .ssh/authorized_keys && \
              cp /configs/stsLauncher.desktop /usr/share/applications && \
              mkdir -p /configs/fonts/truetype/msttcorefonts/ && \
              cp -R /configs/fonts/ /usr/share/fonts/truetype/msttcorefonts && \
              fc-cache -f /usr/share/fonts/truetype/msttcorefonts/"
 
     java.vm.provider "virtualbox" do |vb|
       vb.memory = 4096
       vb.cpus = 4
       vb.name = "java_mint"
       vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
       vb.gui = true
     end
     java.vm.hostname = "java.mint.local"
     java.vm.synced_folder "./configs", "/configs"
     java.vm.synced_folder "/desenvolvimento/tjmt", "/repositorio"
 
   end


   config.vm.define "angular-mint" do |angular|
    # configure the basebox
    angular.vm.box = "epipho/mint-19.3"
   
    angular.vm.network "public_network", ip: "192.168.6.66", bridge: "Intel(R) Ethernet Connection (2) I219-LM"
    angular.vm.network "forwarded_port", guest: 4200, host: 4200
    angular.vm.network "forwarded_port", guest: 5000, host: 80

    angular.vm.provision "shell",
       inline: "apt-get update &&  \
                apt-get install -y software-properties-common && \
                apt-get install -y net-tools && \
                apt-get install snapd"
 
    angular.vm.provision "shell",
     inline: "cat /configs/id_java_env.pub >> .ssh/authorized_keys && \
              cp /configs/stsLauncher.desktop /usr/share/applications && \
              cp /configs/insominia/insominia.lis /etc/apt/sources.list.d"
 
    angular.vm.provider "virtualbox" do |vb|
       vb.memory = 6144
       vb.cpus = 2
       vb.name = "angular_mint"
       vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
       vb.customize ["modifyvm", :id, "--cpuexecutioncap", "90"]
       vb.gui = true
     end

     angular.vm.hostname = "angular.mint.local"
     angular.vm.synced_folder "./configs", "/configs"
     
 
   end

   config.vm.define "angular7-mint" do |angular7|
    # configure the basebox
    angular7.vm.box = "epipho/mint-19.3"
   
    angular7.vm.network "public_network", ip: "192.168.6.67", bridge: "Intel(R) Ethernet Connection (2) I219-LM"
    angular7.vm.network "forwarded_port", guest: 4200, host: 4200

    angular7.vm.provision "shell",
    inline: "cat /configs/id_java_env.pub >> .ssh/authorized_keys"

    angular7.vm.provision "shell",
       inline: "apt-get update &&  \
                apt-get install build-essential -y && \
                apt-get install -y software-properties-common && \
                apt-get install -y net-tools && \
                apt-get install snapd "
    
    angular7.vm.provision "shell",
    inline: " echo insomina && \
            wget --quiet -O - https://insomnia.rest/keys/debian-public.key.asc | apt-key add -"
  
    angular7.vm.provision "shell",
    inline: "echo nvm && \
              apt-get update && \
              wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash"

    angular7.vm.provision "shell",
             inline: "echo set installNVM && \
             mv /root/.nvm /home/vagrant/.nvm && \
             export NVM_DIR='/home/vagrant/.nvm' && \
             [ -s '$NVM_DIR/nvm.sh' ] && \. '$NVM_DIR/nvm.sh'
             [ -s '$NVM_DIR/bash_completion' ] && \. '$NVM_DIR/bash_completion'
             "
              

  
 
    angular7.vm.provider "virtualbox" do |vb|
       vb.memory = 6144
       vb.cpus = 2
       vb.name = "angular7_mint"
       vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
       vb.customize ["modifyvm", :id, "--cpuexecutioncap", "90"]
       vb.gui = true
     end

     angular7.vm.hostname = "angular7.mint.local"
     angular7.vm.synced_folder "./configs", "/configs"     
 
   end

  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "ubuntu/bionic64"
    ansible.vm.network "public_network", ip: "192.168.6.61", bridge: "Intel(R) Ethernet Connection (2) I219-LM"

    ansible.vm.provision "shell",
    inline: "cat /configs/id_java_env.pub >> .ssh/authorized_keys"
   
    ansible.vm.provision "shell",
      inline: "cp /vagrant/id_java_env  /home/vagrant && \
              chmod 600 /home/vagrant/id_java_env && \
              chown vagrant:vagrant /home/vagrant/id_java_env && \
              chown vagrant:vagrant /home"

    ansible.vm.provision "shell",
      inline: "apt-get update &&  \
               apt-get install -y software-properties-common && \
               apt-add-repository -y ppa:ansible/ansible && \
               apt-get update  && \
               apt-get install -y ansible && \
               apt-get remove openjdk* -y && \
               apt-get remove --auto-remove openjdk* -y && \
               apt-get purge openjdk* -y &&
               apt-get purge --auto-remove openjdk* -y && \
               setxkbmap -model abnt2 -layout br -variant abnt2"

    ansible.vm.provision "shell",
        inline: "ansible-playbook /vagrant/ansible/playbook.yml -i /vagrant/ansible/hosts  --ssh-extra-args='-o UpdateHostKeys=yes -o StrictHostKeyChecking=accept-new' 
         "

    ansible.vm.provider "virtualbox" do |vb|
      vb.memory = 248
      vb.cpus = 1
      vb.name = "ansible_ubuntu"
    end
    ansible.vm.synced_folder "./configs", "/configs"
  end
end