Vagrant.configure("2") do |config|

 
  config.vm.define "java-vm" do |java|
   # configure the basebox
   java.vm.box = "fasmat/ubuntu1804-desktop"
  
    java.vm.network "public_network", ip: "192.168.6.60", bridge: "Intel(R) Ethernet Connection (2) I219-LM"

    java.vm.provision "shell",
      inline: "apt-get update &&  \
               apt-get install -y software-properties-common && \
               apt-get install -y net-tools "

    java.vm.provision "shell",
    inline: "cat /configs/id_java_env.pub >> .ssh/authorized_keys && \
             cp /configs/stsLauncher.desktop /usr/share/applications"

    java.vm.provider "virtualbox" do |vb|
      vb.memory = 8192
      vb.cpus = 4
      vb.name = "Java com Eclipse"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.gui = true
    end
    java.vm.hostname = "java-com-eclipse.local"
    java.vm.synced_folder "./configs", "/configs"
    java.vm.synced_folder "/desenvolvimento/tjmt", "/repositorio"
    java.vm.synced_folder ".", "vagrant", disabled: true

  end

  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "ubuntu/bionic64"
    ansible.vm.network "public_network", ip: "192.168.6.61", bridge: "Intel(R) Ethernet Connection (2) I219-LM"

    ansible.vm.provision "shell",
    inline: "cat /configs/id_java_env.pub >> .ssh/authorized_keys"
   
    ansible.vm.provision "shell",
      inline: "cp /vagrant/id_java_env  /home/vagrant && \
              chmod 600 /home/vagrant/id_java_env && \
              chown vagrant:vagrant /home/vagrant/id_java_env"

    ansible.vm.provision "shell",
      inline: "apt-get update &&  \
               apt-get install -y software-properties-common && \
               apt-add-repository -y ppa:ansible/ansible && \
               apt-get update  && \
               apt-get install -y ansible "

    ansible.vm.provision "shell",
        inline: "ansible-playbook /vagrant/ansible/playbook.yml -i /vagrant/ansible/hosts  --ssh-extra-args='-o UpdateHostKeys=yes -o StrictHostKeyChecking=accept-new' 
         "

    ansible.vm.provider "virtualbox" do |vb|
      vb.memory = 248
      vb.cpus = 1
      vb.name = "ansible_ubuntu"
    end
    ansible.vm.synced_folder "./configs", "/configs"
  end
end