Vagrant.configure("2") do |config|

 

  config.vm.define "postgres" do |pg|
    pg.vm.box = "ubuntu/bionic64"
    pg.vm.network "public_network", ip: "192.168.6.62", bridge: "Intel(R) Ethernet Connection (2) I219-LM"
    pg.vm.network "forwarded_port", guest: 22, host: 2220,  auto_correct: true
    pg.vm.network "forwarded_port", guest: 5432, host: 5433,  auto_correct: true

    pg.vm.provision "shell",
      inline: "apt-get update &&  \
               apt-get install -y software-properties-common && \
               apt-get install -y net-tools "

    pg.vm.provision "shell",
      inline: "cat /vagrant/configs/id_java_env.pub >> .ssh/authorized_keys"

    pg.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "postgres_ubuntu"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  end
end